LinkKalenderAkademik=https://docs.google.com/spreadsheets/d/1CB15WxNKar8yHuYV8JX9EBywVmGdKynXSYmyypkzcnA/edit?usp=sharing
LinkJadwalPelajaran=https://drive.google.com/drive/folders/1p5eVzqOkxDzAi1RME6duQEje015wKrjZ?usp=drive_link
JumlahTotalGuru=94
JumlahPengajarKejuruan=38
JumlahPengajarMapel=56
JumlahTenagaKependidikan=19
JumlahTotalSiswa=1601
JumlahSiswaPerempuan=826
JumlahSiswaLaki-Laki=775